stages:
  - analyse
  - build
  - deploy

phpstan:
  stage: analyse
  image: php:8.2
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    - apt-get install unzip
    # on installe composer
    - curl -sS https://getcomposer.org/installer | php
    # on exécute la commande composer install
    - php composer.phar install
  script:
    # on lance l'analyse phpstan
    - vendor/bin/phpstan analyse -c phpstan.neon
  only:
    - main

build:
  stage: build
  image: php:8.2
  before_script:
  script:
    - echo "Build app image"
  only:
    - main

deploy:
  stage: build
  image: php:8.2
  before_script:
  script:
    - echo "Deploy project"
  only:
    - main