stages:
  - analyse
  - build
  - deploy

phpstan:
  stage: analyse
  image: php:8.2
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    - apt-get install unzip
    # on installe composer
    - curl -sS https://getcomposer.org/installer | php
    # on exécute la commande composer install
    - php composer.phar install
  script:
    # on lance l'analyse phpstan
    - vendor/bin/phpstan analyse -c phpstan.neon
  only:
    - main

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    # login to docker hub
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    # Build and push Docker image
    - docker build -t antoinemtx/simple-php-web-app:push-on-main .
    - docker push antoinemtx/simple-php-web-app:push-on-main
  only:
    - main

deploy:
  stage: deploy
  image: php:8.2
  before_script:
  script:
    - echo "Deploy project"
  only:
    - main
