name: phpstan-analysis
run-name: ${{ github.actor }} vient de push sur la main !
on:
  push:
    branches:
      - main

jobs:
  # PHPStan Code Review
  code-review:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code pour faire les actions
      - name: Checkout code
        uses: actions/checkout@v3

        # Config environnement build + installation dépendances
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

        # Revue de Code PHPStan
      - name: Run PHPStan static code analyse
        run: vendor/bin/phpstan analyse -c phpstan.neon

  # Build app
  build-app:
    needs: code-review
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: luciesio/my-repository:push-on-master

  # Deploy project
  deploy-project:
    needs: build-app
    runs-on: ubuntu-latest

    steps:
      - name: Deploy project
        run: echo "Deploy project"