name: phpstan-analysis
run-name: ${{ github.actor }} vient de push sur la main !
on:
  push:
    branches:
      - main

jobs:
  build-and-code-review:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code pour faire les actions
      - name: Checkout code
        uses: actions/checkout@v3

        # Config environnement build + installation dépendances
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

        # Revue de Code PHPStan
      - name: Run PHPStan static code analyse
        run: vendor/bin/phpstan analyse -c phpstan.neon
